" VIM setting
" Abner Chen

let $LANG = 'en'
set langmenu=en     "set menu's language of gvim. no spaces beside '='
set nocompatible    " be iMproved


if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

"------------------------------------------------------------------------------
" vim-plug setting
" https://github.com/junegunn/vim-plug
"------------------------------------------------------------------------------

call plug#begin('~/.vim/plugged')

" Visually displaying indent levels in Vim
Plug 'nathanaelkane/vim-indent-guides'

" File system explorer
Plug 'scrooloose/nerdtree'

" Syntax checking for Vim
Plug 'scrooloose/syntastic'

" Source code tag browser
Plug 'majutsushi/tagbar'

" Lean and mean status/tabline for Vim that's light as air
Plug 'vim-airline/vim-airline'

" Theme repository for vim-airline
Plug 'vim-airline/vim-airline-themes'

" Full path fuzzy file, buffer, mru, tag, ... finder for Vim
Plug 'ctrlpvim/ctrlp.vim'

" Motion enhancement
Plug 'easymotion/vim-easymotion'

" Git wrapper for Vim
Plug 'tpope/vim-fugitive'

" Solarized colorscheme
Plug 'altercation/vim-colors-solarized'

" Tools and environment to make Vim superb for developing with Node.js.
Plug 'moll/vim-node'

" Insert mode auto-completion for quotes, parens, brackets, etc.
Plug 'Raimondi/delimitMate'

" Vim syntax file for Docker's Dockerfile and snippets for snipMate.
Plug 'ekalinin/Dockerfile.vim'

" Search tool
Plug 'mileszs/ack.vim'

" Vim as Python IDE
Plug 'python-mode/python-mode'

" Speed up Vim by updating folds only when called-for
Plug 'Konfekt/FastFold'

" VIM binding to the autocompletion library Jedi
Plug 'davidhalter/jedi-vim'

" To comply with PEP8
Plug 'hynek/vim-python-pep8-indent'

" Base16 for Vim
Plug 'chriskempson/base16-vim'

" Yet Another JavaScript Syntax file for Vim
Plug 'othree/yajs.vim'

" A better JSON for Vim
Plug 'elzr/vim-json'

" Prefer local repo install of eslint over global install with syntastic
Plug 'mtscout6/syntastic-local-eslint.vim'

" Vim syntax plugin for Ansible 2.0
Plug 'pearofducks/ansible-vim'

" Golang support for Vim
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }

" All of your Plugins must be added before the following line
call plug#end()

"------------------------------------------------------------------------------
" General Settings
"------------------------------------------------------------------------------

filetype off          " necessary to make ftdetect work on Linux
syntax on
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins

set nocompatible      " not compatible with the old-fashion vi mode
" Set mouse
set mouse=a
syntax on
filetype on
set autowrite
set number
" Show command line
set showcmd
set showmode
set lcs=tab:>-,trail:-
set list

" Backups
set nobackup
set noswapfile

" Always show current position
set ruler

set expandtab
set smarttab
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set wrap

" Highlight search results
set hlsearch
" Makes search act like search in modern browsers
set incsearch
set laststatus=2
set cursorline
set backspace=2
set colorcolumn=120
set wildmenu
set cpo-=<
set wcm=<C-Z>
set foldmethod=indent
set foldnestmax=5
set formatoptions=mtcql
set scrolloff=2
set t_Co=256
set background=dark

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=

set encoding=utf-8
set clipboard=unnamed

autocmd FileType php setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType ruby setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType php setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth=120
autocmd FileType coffee,javascript,json,yaml setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth=120
autocmd FileType html,htmldjango,xhtml,haml setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=0
autocmd FileType sass,scss,css setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120

" change cursor shape for insert mode
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

"colorscheme solarized
let base16colorspace=256  " Access colors present in 256 colorspace"
colorscheme base16-default-dark

if has("gui_running")
    if has("gui_gtk2")
        set guifont=Inconsolata\ 12
    elseif has("gui_macvim")
        set guifont=Source_Code_Pro_Medium:h14
    elseif has("gui_win32")
        set guifont=Source_Code_Pro_Medium:h12:cANSI
    endif
endif

"------------------------------------------------------------------------------
" Key Mapping
"
" Commands                        Mode
" --------                        ----
" nmap, nnoremap, nunmap          Normal mode
" imap, inoremap, iunmap          Insert and Replace mode
" vmap, vnoremap, vunmap          Visual and Select mode
" xmap, xnoremap, xunmap          Visual mode
" smap, snoremap, sunmap          Select mode
" cmap, cnoremap, cunmap          Command-line mode
" omap, onoremap, ounmap          Operator pending mode
"------------------------------------------------------------------------------
map tn              :tabnext<CR>
map tp              :tabprev<CR>
map te              :tabnew 
map tc              :tabclose<CR>
map vs              :vsplit 

nmap <Tab>          v>
nmap <S-tab>        v<
nnoremap <A-J>      :m+<CR>==
nnoremap <A-K>      :m-2<CR>==
nnoremap <Space>    za
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

inoremap <A-J>      <Esc>:m+<CR>==gi
inoremap <A-K>      <Esc>:m-2<CR>==gi

vmap <Tab>          >gv
vmap <S-Tab>        <gv
vnoremap <A-J>      :m'>+<CR>gv=gv
vnoremap <A-K>      :m-2<CR>gv=gv
vnoremap <Space>    zf

cmap <C-A>          <Home>
cmap <C-E>          <End>
cnoremap <C-B>      <Left>
cnoremap <C-D>      <Del>
cnoremap <C-F>      <Right>
cnoremap <C-N>      <Down>
cnoremap <C-P>      <Up>
cnoremap <Esc><C-B> <S-Left>
cnoremap <Esc><C-F> <S-Right>

if has("gui_running")
    " paste
    map <C-V>       "+gP
    " cut
    vnoremap <C-X>  "+x
    " copy
    vnoremap <C-C>  "+y
endif

"------------------------------------------------------------------------------
" vim-airline
"------------------------------------------------------------------------------
"let g:airline_theme = 'solarized'
let g:airline_theme = 'base16color'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#syntastic#enabled = 1

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

"------------------------------------------------------------------------------
" vim-indent-guides
"------------------------------------------------------------------------------
let g:indent_guides_auto_colors = 0
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=233
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=236

"------------------------------------------------------------------------------
" CtrlP
"------------------------------------------------------------------------------
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_custom_ignore = '\v[\/](\.(git|hg|svn)|(bower_components|node_modules|__pycache__))$'

"------------------------------------------------------------------------------
" tagbar
"------------------------------------------------------------------------------
nnoremap <silent> <F9> :TagbarToggle<CR>

"------------------------------------------------------------------------------
" nerdtree
"------------------------------------------------------------------------------
map <C-n> :NERDTreeToggle<CR>
let g:NERDTreeWinPos = "left"
let NERDTreeDirArrows = 1

"------------------------------------------------------------------------------
" syntastic
"------------------------------------------------------------------------------
let g:syntastic_python_python_exec = '/usr/local/bin/python3'
let g:syntastic_ignore_files = ['\.py$']
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_error_symbol = '❌'
let g:syntastic_style_error_symbol = '⁉️'
let g:syntastic_warning_symbol = '⚠️'
let g:syntastic_style_warning_symbol = '💩'
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }

"------------------------------------------------------------------------------
" YouCompleteMe
"------------------------------------------------------------------------------
let g:ycm_complete_in_comments = 1
set completeopt-=preview
let g:ycm_seed_identifiers_with_syntax = 1

"------------------------------------------------------------------------------
" Python-mode
"------------------------------------------------------------------------------
let g:pymode_python = 'python3'
let g:pymode_rope_completion = 0
let g:pymode_rope_complete_on_dot = 0
"let g:pymode_rope_completion_bind = '<C-k>'
let g:pymode_rope_goto_definition_bind = "<C-]>"
let g:pymode_lint_checkers = ['python', 'pyflakes', 'pep8']

"------------------------------------------------------------------------------
" jedi-vim
"------------------------------------------------------------------------------
let g:jedi#force_py_version = 3
let g:jedi#use_splits_not_buffers = "top"
let g:jedi#goto_definitions_command = "<C-]>"
let g:jedi#completions_command = "<C-k>"

"------------------------------------------------------------------------------
" vim-go
"------------------------------------------------------------------------------
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_fmt_experimental = 1
let g:go_fmt_command = "goimports"
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet']
let g:go_metalinter_deadline = '5s'
